- name: restart_jitsi
  service:
    name: jitsi-videobridge2
    state: restarted
- name: restart_nginx
  service:
    name: nginx
    state: restarted
- name: reload_nginx
  service:
    name: nginx
    state: reloaded
