- name: Ensure universe
  apt_repository:
    repo: deb {{ apt_mirror }} {{ ansible_distribution_release }} universe
    state: present
    update_cache: no
    filename: universe
- name: Ensure universe-updates
  apt_repository:
    repo: deb {{ apt_mirror }} {{ ansible_distribution_release }}-updates universe
    state: present
    update_cache: no
    filename: universe
- name: Ensure universe-security
  apt_repository:
    repo: deb {{ apt_mirror }} {{ ansible_distribution_release }}-security universe
    state: present
    update_cache: no
    filename: universe
