# Group vars for the group ubuntu.
---
users:
  ber:
    name: "Bèr Kessels"
    key: https://github.com/berkes.keys
    password: "{{ vault_enabled_users.ber.password }}"
    munin_password: "{{ vault_enabled_users.ber.munin_password }}"
  bjorn:
    name: "Bjorn Wijers"
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDR+fE8bfiPx0Ae/5HjmsYcb3xvI/7Zs3zMebUi9/M4qxV01sYWncqjCHqSctW7Yz9wYINR1UMsTAWUf/JLUxQaBBqnZnwEwlTF601l8U/Z6neeL9GhRscbsCGYnGUuTZX5KrApOLAKm1iCL+C0Rqh/UIH+cnOxs0o2giQVCj5MpvywEU9TOtL0sK5u1XzUEGAcfvTvgnl0X9xAx5C7jAPm3Efnyf3idlm+A7rMv3wGR/LT7KVHzYxcWByMQoLSlXZ0ia881Ed3UDHlad06u1LmdJ7K/ljSIE8EpRfJaNZ9WC6IkiBlNN21SyRv81TG8S05HUOEuAlLkRVF/TIdQOQmmwuB61d1GCbDF8Eo+8F6Qwpr7fkVYmp11P/9FQZ4UP0s9wiT84/pqaedKHrppuqWGfV7vpheYNWEw626gLrjSHkrm3zj0fuUFB+hNM+MJ64IF53UMWLaODpxiG5pUqoaoopSfnogwMBtUHl7Jq9kRV7SD/6+QKAZO9wbr9fvTq9OuwGtzI/CQx1xFDVNwYblgQJB+azt43OpW8AYTvFbj0PERa7TBIHmQZlE1ixUOhdoeI0+9x+F4H5/jCRCl+Vlbztk+Hd8mDHeAlgEw/nsqEN+TDbWW/lYdBtKALdUS91PiMWM1Ef27LGxnc3+z8xr5XmBWAm8H9Kmad7onRKmRw== burobjorn@burobjorn.nl"
    password: "{{ vault_enabled_users.bjorn.password }}"
    munin_password: "{{ vault_enabled_users.bjorn.munin_password }}"

deploy_keys:
  - https://github.com/berkes.keys
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDR+fE8bfiPx0Ae/5HjmsYcb3xvI/7Zs3zMebUi9/M4qxV01sYWncqjCHqSctW7Yz9wYINR1UMsTAWUf/JLUxQaBBqnZnwEwlTF601l8U/Z6neeL9GhRscbsCGYnGUuTZX5KrApOLAKm1iCL+C0Rqh/UIH+cnOxs0o2giQVCj5MpvywEU9TOtL0sK5u1XzUEGAcfvTvgnl0X9xAx5C7jAPm3Efnyf3idlm+A7rMv3wGR/LT7KVHzYxcWByMQoLSlXZ0ia881Ed3UDHlad06u1LmdJ7K/ljSIE8EpRfJaNZ9WC6IkiBlNN21SyRv81TG8S05HUOEuAlLkRVF/TIdQOQmmwuB61d1GCbDF8Eo+8F6Qwpr7fkVYmp11P/9FQZ4UP0s9wiT84/pqaedKHrppuqWGfV7vpheYNWEw626gLrjSHkrm3zj0fuUFB+hNM+MJ64IF53UMWLaODpxiG5pUqoaoopSfnogwMBtUHl7Jq9kRV7SD/6+QKAZO9wbr9fvTq9OuwGtzI/CQx1xFDVNwYblgQJB+azt43OpW8AYTvFbj0PERa7TBIHmQZlE1ixUOhdoeI0+9x+F4H5/jCRCl+Vlbztk+Hd8mDHeAlgEw/nsqEN+TDbWW/lYdBtKALdUS91PiMWM1Ef27LGxnc3+z8xr5XmBWAm8H9Kmad7onRKmRw== burobjorn@burobjorn.nl"

swapfile_file: "/swap"
swapfile_size: "1G"

firewall_blacklist:
  -
firewall_remove_blacklist:
  -

additional_packages:
  - nethogs
  - nginx # jitsi_firewall needs nginx to access the ufw profile

apt_mirror: http://ftp.snt.utwente.nl/pub/os/linux/ubuntu/

## Jitsi role needs this.
certbot_enabled: true
certbot_admin_email: ber@berk.es

use_custom_jitsi_config_vars: true
jitsi_config:
  hosts:
    domain: "{{ jitsi_domain }}"
    muc: "conference.{{ jitsi_domain }}"
    # anonymousdomain: guest.example.com
    # authdomain: {{ jitsi_domain }}
    # jirecon: jirecon.{{ jitsi_domain }}
    # call_control: callcontrol.{{ jitsi_domain}}
    # focus: focus.{{ jitsi_domain }}
  bosh: "//{{ jitsi_domain }}/http-bind"
  clientNode: "http://jitsi.org/jitsimeet"

  testing:
    enableFirefoxMulticast: false
    p2pTestMode: false
    # testMode: false
    # noAutoPlayVideo: false
  # webrtcIceUdpDisable: false
  # webrtcIceTcpDisable: false
  # disableAudioLevels: false
  # startAudioOnly: false
  # startAudioMuted: 10
  # startWithAudioMuted: false
  # startSilent: false
  # resolution: 720
  # constraints:
    # video:
      # aspectRatio: 16 / 9
        # height:
          # ideal: 720
          # max: 720
          # min: 240
  # disableSimulcast: false
  # enableLayerSuspension: false
  # startVideoMuted: 10
  # startWithVideoMuted: false
  # preferH264: true
  # disableH264: false
  desktopSharingChromeExtId: null
  desktopSharingChromeSources: [ 'screen', 'window', 'tab' ]
  desktopSharingChromeMinExtVersion: '0.1'
  # desktopSharingChromeDisabled: false
  # desktopSharingFirefoxDisabled: false
  # desktopSharingFrameRate:
    # min: 5
    # max: 5
  # startScreenSharing: false

  # fileRecordingsEnabled: false
  # dropbox:
    # appKey: "<APP_KEY>"
    # redirectURI: "https://{{ jitsi_domain }}/subfolder/static/oauth.html"
  # fileRecordingsServiceEnabled: false
  # fileRecordingsServiceSharingEnabled: false

  # liveStreamingEnabled: false
  # transcribingEnabled: false
  # autoCaptionOnRecord: false

  channelLastN: -1
  # disableRtx: false
  # enableTcc: true
  # enableRemb: false
  # minParticipants: 2
  # useStunTurn: true
  # useIPv6: true
  # openBridgeChannel: true

  # useNicks: false
  # requireDisplayName: true
  enableWelcomePage: true
  # enableClosePage: false
  # disable1On1Mode: false
  defaultLanguage: 'nl' # BK 2020-04-02
  enableUserRolesBasedOnToken: false
  # enableFeaturesBasedOnToken: false
  # lockRoomGuestEnabled: false
  # roomPasswordNumberOfDigits: 10
  # default: roomPasswordNumberOfDigits: false
  # noticeMessage: ''
  # enableCalendarIntegration: false

  # gatherStats: false
  # callStatsId: ''
  # callStatsSecret: ''
  # enableDisplayNameInStats: false
  # enableEmailInStats: false

  # disableThirdPartyRequests: false
  p2p:
    enabled: true
    # useStunTurn: true
    stunServers:
      - urls: 'stun:meet-jit-si-turnrelay.jitsi.net:443'
    # iceTransportPolicy: 'all'
    preferH264: true
    # disableH264: false
    # backToP2PDelay: 5
  analytics: {}
    # googleAnalyticsTrackingId: 'your-tracking-id-UA-123456-1'
    # amplitudeAPPKey: '<APP_KEY>'
    # scriptURLs:
    #   - "libs/analytics-ga.min.js"
    #   - "https://example.com/my-custom-analytics.js"
  deploymentInfo: {}
    # shard: "shard1"
    # region: "europe"
    # userRegion: "asia"
  localRecording: {}
    # enabled: true
    # format: 'flac'
  e2eping: {}
    # pingInterval: 10000
    # analyticsInterval: 60000
  # DesktopSharingSourceDevice: 'sample-id-or-label'
  # disableDeepLinking: false
  # disableLocalVideoFlip: false
  deploymentUrls: {}
    # userDocumentationURL: 'https:#docs.example.com/video-meetings.html'
    # downloadAppsUrl: 'https:#docs.example.com/our-apps.html'
